[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
rustflags = ["-C", "link-args=-rdynamic"]

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-args=-rdynamic", "-C", "target-feature=+fp16"]

# [target.aarch64-apple-darwin]
# linker = "clang"
# rustflags = ["-C", "link-args=-dynamiclib"]

# [target.x86_64-apple-darwin]
# linker = "clang"
# rustflags = ["-C", "link-args=-dynamiclib"]

[env]
